IF OBJECT_ID('Tickets', 'U') IS NOT NULL DROP TABLE Tickets;
IF OBJECT_ID('Concerts', 'U') IS NOT NULL DROP TABLE Concerts;
IF OBJECT_ID('Users', 'U') IS NOT NULL DROP TABLE Users;

CREATE TABLE Users (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Email NVARCHAR(255) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(500) NOT NULL
);

CREATE TABLE Concerts (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    Location NVARCHAR(255) NOT NULL,
    Date DATETIME2 NOT NULL,
    Price DECIMAL(10,2) NOT NULL
);

CREATE TABLE Tickets (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    UserId NVARCHAR(255) NOT NULL,
    ConcertId INT NOT NULL,
    Quantity INT NOT NULL,
    CONSTRAINT FK_Tickets_Concerts FOREIGN KEY (ConcertId) REFERENCES Concerts(Id)
);
